---
- name: check the value of required fact cvd_device_role
  fail:
    msg: "missing or invalid fact: device_role"
  when: cvd_device_role is not defined or cvd_device_role not in cvd_settings_device_roles

- name: check the value of required fact cvd_device_model
  fail:
    msg: "missing or invalid fact: device_model"
  when: cvd_device_model is not defined or cvd_device_model not in cvd_settings_device_models

- name: get the current running-config from the device
  ios_command:
    commands: show running-config
  connection: network_cli
  register: configuration

- name: include device role specific tasks
  include_tasks: "includes/{{ cvd_device_role }}/main.yaml"

- name: save the current running-config to startup-config
  ios_config:
    save_when: modified
    diff_against: intended
    intended_config: "{{ configuration.stdout }}"
  connection: network_cli
