---
- name: display device model
  debug:
    msg: "device model is {{ cvd_device_model }}"

- name: display device role
  debug:
    msg: "device role is {{ cvd_device_role }}"

- name: create destination path (if necssary)
  file:
    path: "{{ dest }}/{{ item.path }}"
    state: directory
  with_filetree: "{{ role_path }}/templates"
  when: item.state == 'directory'

- name: dump xml template to disk
  template:
    src: "{{ item.src }}"
    dest: "{{ dest }}/{{ item.path.replace('.j2', '') }}"
    trim_blocks: yes
  with_filetree: "{{ role_path }}/templates"
  when: item.state == 'file'

