---
# tasks file for cisco-cvd-campus-lan-layer2
#
- name: set role supported targets
  set_fact:
    cvd_targets:
      - configure
      - hostvars
      - dump
      - noop

- name: validate the value for target
  fail:
    msg: "invalid target specified, expected one of {{ cvd_targets }}, got {{ target }}"
  when: target | default('configure') not in cvd_targets

- name: include target tasks and run
  include_tasks: "{{ target | default('configure') }}.yaml"

