---
- name: enable spanning-tree bpdu guard
  netconf_config:
    xml: "{{ lookup('template', 'templates/common/stp_bpdu_guard.xml.j2') }}"

- name: configure loopback 0 address
  netconf_config:
    xml: "{{ lookup('template', 'templates/distribution/loopback_ip.xml.j2') }}"
  when: cvd_loopback0_address is defined

- name: configure out-of-band management interface (if necessary)
  block:
    - name: configure out-of-band interface address
      netconf_config:
        xml: "{{ lookup('template', 'templates/distribution/oob_ip.xml.j2') }}"

    - name: exclude out-of-band management interface from vss shutdown
      ios_config:
        lines: "dual-active exclude interface {{ oob_interface['interface']  }}"
        parents: "switch virtual domain {{ vss_domain }}"
      when: model | string in ['6500']
      connection: network_cli
  when: oob_interface

- name: configure system process to use loopback interface address
  netconf_config:
    xml: "{{ lookup('template', 'templates/distribution/sys_process_source_iface.xml.j2') }}"

