---
- name: configure the device hostname
  netconf_config:
    src: "{{ lookup('template', 'common/hostname.xml.j2') }}"
  when: hostname | default(ansible_access_switch_hostname)

- name: set vtp mode to transparent
  netconf_config:
    src: "{{ lookup('template', 'common/vtp.xml.j2') }}"

- name: enable rapid per-vlan spanning-tree (pvst+)
  netconf_config:
    src: "{{ lookup('template', 'common/stp.xml.j2') }}"

- name: set spanning-tree root for all vlans
  ios_config:
    commands: spanning-tree vlan 1-4094 root primary
  connection: network_cli

- name: enable unidirectional link detection (udld)
  netconf_config:
    src: "{{ lookup('template', 'common/udld.xml.j2') }}"

- name: enable automatic recovery from port error disabled state
  netconf_config:
    src: "{{ lookup('template', 'common/errdisable.xml.j2') }}"

- name: configure dns name servers
  netconf_config:
    src: "{{ lookup('template', 'common/dns.xml.j2') }}"
  when: name_servers | default(access_switch_name_servers)

- name: configure device management protocols
  netconf_config:
    src: "{{ lookup('template', 'common/mgmt_protocols.xml.j2') }}"

- name: enable snmp ro and rw community strings
  netconf_config:
    src: "{{ lookup('template', 'common/snmp.xml.j2') }}"

  # setting when to false effectively disables the task from running
  # TODO fix template variables
- name: configure acl to secure management traffic
  netconf_config:
    src: "{{ lookup('template', 'common/mgmt_acl.xml.j2') }}"
  when: false

- name: configure local accounts
  netconf_config:
    src: "{{ lookup('template', 'common/local_login.xml.j2') }}"
  when: local_accounts | default(access_switch_local_accounts)

- name: configure tacacs+ servers
  netconf_config:
    src: "{{ lookup('template', 'common/tacacs.xml.j2') }}"

- name: configure ntp servers
  netconf_config:
    src: "{{ lookup('template', 'common/ntp.xml.j2') }}"
