- name: enable spanning-tree bpdu guard
  netconf_config:
    src: "{{ lookup('template', 'stp/bpdu_guard.xml.j2') }}"

- name: configure





- name: BUILD LOOPBACK_IP XML DATA
  template:
    src: loopback_ip.j2
    dest: "{{ configs_dir }}/{{ inventory_hostname }}/loopback_ip.xml"

- name: PUSH NETCONF TO REMOTES
  netconf_config:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_ssh_pass }}"
    src: "{{ configs_dir }}/{{ inventory_hostname }}/loopback_ip.xml"




- name: BUILD OOB_IP XML DATA
  template:
    src: oob_ip.j2
    dest: "{{ configs_dir }}/{{ inventory_hostname }}/oob_ip.xml"

- name: PUSH NETCONF TO REMOTES
  netconf_config:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_ssh_pass }}"
    src: "{{ configs_dir }}/{{ inventory_hostname }}/oob_ip.xml"




- name: BUILD VSS EXCLUDE SUMMARIZATION CONFIG DATA
  template:
    src: vss_exclude.j2
    dest: "{{ configs_dir }}/{{ inventory_hostname }}/vss_exclude.cfg"

- name: PUSH CONFIG TO REMOTES
  ios_config:
    provider: "{{ provider }}"
    src: "{{ configs_dir }}/{{ inventory_hostname }}/vss_exclude.cfg"

- name: WAIT AN ARBITRARY PERIOD FOR CONFIG SYNC
  pause:
    prompt: "Wait for configuration synchronization."
    seconds: 60
