---
- name: configure the device hostname
  netconf_config:
    xml: "{{ lookup('template', 'templates/common/hostname.xml.j2') }}"

- name: set vtp mode to transparent
  netconf_config:
    xml: "{{ lookup('template', 'templates/common/vtp_transparent_mode.xml.j2') }}"

- name: enable spanning-tree rapid per-vlan spanning-tree (pvst+)
  netconf_config:
    xml: "{{ lookup('template', 'templates/common/stp_rapid_pvst.xml.j2') }}"

- name: enable unidirectional link detection (udld)
  netconf_config:
    xml: "{{ lookup('template', 'templates/common/udld_enable.xml.j2') }}"

- name: enable automatic recovery from port error disabled state
  netconf_config:
    xml: "{{ lookup('template', 'templates/common/errdisable.xml.j2') }}"

- name: configure dns name servers
  netconf_config:
    xml: "{{ lookup('template', 'templates/common/name_servers.xml.j2') }}"
  when: cvd_name_servers

- name: configure device management protocols
  netconf_config:
    xml: "{{ lookup('template', 'templates/common/protocols.xml.j2') }}"

- name: enable snmp ro and rw community strings
  netconf_config:
    xml: "{{ lookup('template', 'templates/common/snmp.xml.j2') }}"

  # setting when to false effectively disables the task from running
  # TODO fix template variables
- name: configure acl to secure management traffic
  netconf_config:
    xml: "{{ lookup('template', 'templates/common/management_acl.xml.j2') }}"
  when: false

- name: configure local accounts
  netconf_config:
    xml: "{{ lookup('template', 'templates/common/local_login.xml.j2') }}"

- name: configure tacacs+ servers
  netconf_config:
    xml: "{{ lookup('template', 'templates/common/tacacs.xml.j2') }}"

- name: configure ntp servers
  netconf_config:
    xml: "{{ lookup('template', 'templates/common/ntp.xml.j2') }}"
